version: 1.0.{build}
branches:
  only:
  - master
  
build:
  verbosity: minimal
  project: ReadMe.sln

before_build:
- ps: nuget restore ./ReadMe.sln

after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single  ReadMe.Web.Tests\bin\Debug\ReadMe.Web.Tests.dll"